### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by akshaydeepakm44** [KIET-NEST-PROJECTS-KBH/D-3F-302C#3]
You need to create a login page as per our discussion and make it resonable. And  i want a neat presentation of your work.

**Comment by Shankar1920** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f4f4f4;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
        }
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        .btn {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Login</h2>
        <form action="login_process.php" method="POST">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn">
            </div>
        </form>
    </div>
</body>
</html>

**Comment by Shankar1920** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f4f4f4;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
        }
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        .btn {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Login</h2>
        <form action="login_process.php" method="POST">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn">
            </div>
        </form>
    </div>
</body>
</html>

**Comment by Shankar1920** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Animated Login From</title>
    <link/>
    

    
  </head>
  <style>
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  body {
            background: linear-gradient(45deg, #ff00ff, #8809ff, #0b65ff, #3a77e3, #8400ff, #ff0000);
            background-size: 400% 400%;
            animation: gradient 5s linear infinite;
        }

        @keyframes gradient {
            0% {
                background-position: 100% 0;
            }
            100% {
                background-position: 0 100%;
            }
        }
  body{
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      letter-spacing: 1px;
      background-color: #0c1022;
  }
  .login_form_container{
      position: relative;
      width: 400px;
      height: 470px;
      max-width: 400px;
      max-height: 470px;
      background: #040717;
      border-radius: 50px 5px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      margin-top: 70px;
  }
  .login_form_container::before{
      
      position: absolute;
      width: 170%;
      height: 170%;
      content: '';
      background-image: conic-gradient(transparent, transparent, transparent, #ee00ff);
      animation: rotate_border 6s linear infinite;
  
  }
  .login_form_container::after{
      
      position: absolute;
      width: 170%;
      height: 170%;
      content: '';
      background-image: conic-gradient(transparent, transparent, transparent, #00ccff);
      animation: rotate_border 6s linear infinite;
      animation-delay: -3s;
  }
  @keyframes rotate_border{
      0%{
          transform: rotate(0deg);
      }
      100%{
          transform: rotate(360deg);
      }
  }
  .login_form{
      position: absolute;
      content: '';
      background-color: #0c1022;
      border-radius: 50px 5px;
      inset: 5px;
      padding: 50px 40px;
      z-index: 10;
      color: #00ccff;
  
  } 
  h2{
      font-size: 40px;
      font-weight: 600;
      text-align: center;
  }
  .input_group{
      margin-top: 40px;
      position:relative;
      display:flex;
      align-items: center;
      justify-content: start;
  }
  .input_text{
      width: 95%;
      height: 30px;
      background: transparent;
      border: none;
      outline: none;
      border-bottom: 1px solid #00ccff;
      font-size: 20px;
      padding-left: 10px;
      color: #00ccff;
  
  }
  ::placeholder{
      font-size: 15px;
      color: #00ccff52;
      letter-spacing: 1px;
  
  }
  .fa{
      font-size: 20px;
  
  }
  #login_button{
      position: relative;
      width: 300px;
      height: 40px;
      transition: 1s;
      margin-top: 70px;
  
  
  }
  #login_button a{
      position: absolute;
      width: 100%;
      height: 100%;
      text-decoration: none;
      z-index: 10;
      cursor: pointer;
      font-size: 22px;
      letter-spacing: 2px;
      border: 1px solid #00ccff;
      border-radius: 50px;
      background-color: #0c1022;
      display: flex;
      justify-content: center;
      align-items: center;
  }
  .fotter {
      margin-top: 30px;
      display: flex;
      justify-content: space-between;
  
  }
  .fotter a{
      text-decoration: none;
      cursor: pointer;
      font-size: 18px;
  }
  .glowIcon {
      text-shadow: 0 0 10px #00ccff;
  
  }
  .end-link{
    text-align: end;
      position: absolute;
      bottom: 0;
      right: 20px;
      color: aqua;
      margin: 10px;
      text-decoration: none;
      font-size: larger;
  }
  
  </style>
  <body>
    <div class="login_form_container">
      <div class="login_form">
        <h2>Login</h2>
        <div class="input_group">
          <i class="user"></i>
          <input
            type="text"
            placeholder="Username"
            class="input_text"
            autocomplete="off"
          />
        </div>
        <div class="input_group">
          <i class="unlock"></i>
          <input
            type="password"
            placeholder="Password"
            class="input_text"
            autocomplete="off"
          />
        </div>
        <div class="button_group" id="login_button">
          <a>Submit</a>
        </div>
        <div class="fotter">
          <a  style="color: #ee00ff;" href="file:///F:/forgot.html">Forgot Password ?</a>
          <a style="color: #ee00ff;" href="file:///F:/signin.html">Singin</a>
        </div>
      </div>
    </div>

    
  </body>
  
  <a class="end-link" href="file:///F:/Home.html">Home</a>
</html>
